#Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: maven:3.3-jdk-8

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: /Users/i842164/infra/src/Super-Mario/YaaS-Pipelines/YCD-1109-circleCI

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
      working_directory: /
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Dependancies
          command: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Clean
          command: ls -la | mvn -B clean
      - run:
          name: Compile
          command: mvn -B compile
      - run:
          name: Unit test
          command: mvn -B test
      - run:
          name: Install
          command: mvn -B install -DskipTests
      - run:
          name: Create artifacts
          command: mv target/*.war /target/application.war

      # run tests!
      - run:
          name: Integration Test
          command: mvn integration-test

     - store_artifacts:
         path: /target/application.war
         destination: application.war
